doc-warnings: true
test-warnings: true
strictness: veryhigh
max-line-length: 120
python-targets: [2, 3]
pep8:
    full: true
pyflakes:
    run: true
mccabe:
    run: true
inherits: [flake8]
autodetect: true
